=== tuxBurner/jmimemagic/src/test/resources/magic_1_0.dtd
<!ELEMENT magic (info?,match-list)>
<!ELEMENT info (version?,author?,description?)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT match-list (match*)>
<!ELEMENT match (mimetype,extension,description,test,match-list?)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT test (#PCDATA)>
<!ATTLIST test offset CDATA "0">
<!ATTLIST test length CDATA "0">
<!ATTLIST test type CDATA "string">
<!ATTLIST test bitmask CDATA "">
<!ATTLIST test comparator CDATA "=">

=== tuxBurner/jmimemagic/src/test/resources/magic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE magic PUBLIC "-//jmimemagic//DTD magic config 1.0//EN" "magic_1_0.dtd">
<magic>
<info>
<version>0.1</version>
<author>s.hardt</author>
<description>magic file for movies</description>
</info>
<match-list>
<match>
  <mimetype>video/mp4</mimetype>
  <extension></extension>
  <description>MP4</description>
  <test type="regex" offset="0" length="20"  comparator="=">/\A....ftyp/s</test>
</match>
<match>
	<mimetype>video/mpeg</mimetype>
	<extension>mpg</extension>
	<description>MPEG video stream data</description>
	<test offset="0" type="belong" comparator="=">0x1b3</test>
</match>
<match>
	<mimetype>video/mpeg</mimetype>
	<extension>mpg</extension>
	<description>MPEG system stream data</description>
	<test offset="0" type="belong" comparator="=">0x1ba</test>
</match>
<match>
	<mimetype>???</mimetype>
	<extension>???</extension>
	<description>Silicon Graphics movie file</description>
	<test offset="0" type="string" comparator="=">MOVI</test>
</match>
<match>
	<mimetype>video/quicktime</mimetype>
	<extension>mov</extension>
	<description>Apple QuickTime movie file (moov)</description>
	<test offset="4" length="4" type="string" comparator="=">moov</test>
</match>
<match>
	<mimetype>video/quicktime</mimetype>
	<extension>mov</extension>
	<description>Apple QuickTime movie file (mdat)</description>
	<test offset="4" length="4" type="string" comparator="=">mdat</test>
</match>

<match>
	<mimetype>???</mimetype>
	<extension>???</extension>
	<description>RIFF (little-endian) data</description>
	<test offset="0" length="4" type="string" comparator="=">RIFF</test>
	<match-list>
		<match>
			<mimetype>???</mimetype>
			<extension>???</extension>
			<description>multimedia movie</description>
			<test offset="8" length="4" type="string" comparator="=">RMMP</test>
		</match>		
		<match>
			<mimetype>video/avi</mimetype>
			<extension>???</extension>
			<description>AVI</description>
			<test offset="8" length="3" type="string" comparator="=">AVI </test>
		</match>
	</match-list>
</match>

<match>
	<mimetype>???</mimetype>
	<extension>???</extension>
	<description>RIFF (big-endian) data</description>
	<test offset="0" length="4" type="string" comparator="=">RIFX</test>
	<match-list>
		<match>
			<mimetype>???</mimetype>
			<extension>???</extension>
			<description>multimedia movie</description>
			<test offset="8" type="string" comparator="=">RMMP</test>
		</match>
		<match>
			<mimetype>video/avi</mimetype>
			<extension>???</extension>
			<description>AVI</description>
			<test offset="8" length="3" type="string" comparator="=">AVI </test>
		</match>
	</match-list>
</match>

</match-list>
</magic>
